package defpackage;

/* compiled from: r8-map-id-39a5fd6059330804833c2374f28b82f3b8aef423af32ebd824babcd2cdcd11b4 */
/* renamed from: j50, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public abstract class AbstractC1515j50 {
    public static final G2 a;
    public static final G2 b;
    public static final G2 c;
    public static final G2 d;
    public static final G2 e;
    public static final G2 f;
    public static final G2 g;

    static {
        new G2(0, "VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK");
        new G2(0, "OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER");
        new G2(3, "SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE");
        new G2(1, "DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS");
        new G2(4, "START_SAFE_BROWSING", "START_SAFE_BROWSING");
        new G2(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST");
        new G2(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST");
        new G2(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST");
        new G2(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST");
        new G2(4, "SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL");
        new G2(1, "SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE");
        new G2(1, "SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE");
        new G2(1, "SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS");
        new G2(1, "SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS");
        new G2(1, "SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS");
        new G2(1, "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST");
        new G2(0, "RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR");
        new G2(0, "RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR");
        new G2(1, "SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS");
        new G2(4, "SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT");
        new G2(1, "WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT");
        new G2(0, "WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION");
        new G2(0, "WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE");
        new G2(4, "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY");
        new G2(4, "SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED");
        new G2(4, "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL");
        new G2(0, "WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE");
        new G2(0, "WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE");
        a = new G2(2, "WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER");
        new G2(0, "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK");
        new G2(0, "CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL");
        new G2(0, "POST_WEB_MESSAGE", "POST_WEB_MESSAGE");
        new G2(0, "WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE");
        new G2(3, "GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT");
        new G2(3, "GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT");
        new G2(6, "GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER");
        new G2(6, "WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE");
        new G2(5, "TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE");
        new C1952oX();
        new C1952oX();
        new C1952oX();
        new G2(6, "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE");
        new C1355h50();
        new G2(2, "PROXY_OVERRIDE", "PROXY_OVERRIDE:3");
        b = new G2(2, "MULTI_PROCESS", "MULTI_PROCESS_QUERY");
        c = new G2(6, "FORCE_DARK", "FORCE_DARK");
        d = new G2(2, "FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR");
        e = new G2(2, "WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER");
        new G2(2, "DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1");
        new G2(2, "PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS");
        new G2(2, "GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER");
        new G2(2, "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY");
        new G2(2, "GET_COOKIE_INFO", "GET_COOKIE_INFO");
        new G2(2, "REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST");
        new G2(2, "USER_AGENT_METADATA", "USER_AGENT_METADATA");
        new C1436i50(0, "MULTI_PROFILE", "MULTI_PROFILE");
        new G2(2, "ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR");
        new G2(2, "WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS");
        new G2(2, "MUTE_AUDIO", "MUTE_AUDIO");
        new G2(2, "WEB_AUTHENTICATION", "WEB_AUTHENTICATION");
        new G2(2, "SPECULATIVE_LOADING_STATUS", "SPECULATIVE_LOADING");
        new G2(2, "BACK_FORWARD_CACHE", "BACK_FORWARD_CACHE");
        new G2(2, "DELETE_BROWSING_DATA", "WEB_STORAGE_DELETE_BROWSING_DATA");
        new C1436i50(1, "PREFETCH_URL_V4", "PREFETCH_URL_V4");
        new G2(2, "IMPLEMENTATION_ONLY_FEATURE", "ASYNC_WEBVIEW_STARTUP");
        new G2(2, "DEFAULT_TRAFFICSTATS_TAGGING", "DEFAULT_TRAFFICSTATS_TAGGING");
        new G2(2, "PRERENDER_URL_V2", "PRERENDER_URL_V2");
        new G2(2, "SPECULATIVE_LOADING_CONFIG_V2", "SPECULATIVE_LOADING_CONFIG_V2");
        new G2(2, "SAVE_STATE", "SAVE_STATE");
        new G2(2, "WEB_VIEW_NAVIGATION_CLIENT_BASIC_USAGE", "WEB_VIEW_NAVIGATION_CLIENT_BASIC_USAGE");
        f = new G2(2, "CACHE_PROVIDER", "PROVIDER_WEAKLY_REF_WEBVIEW");
        g = new G2(2, "PAYMENT_REQUEST", "PAYMENT_REQUEST");
        new G2(2, "WEBVIEW_BUILDER", "WEBVIEW_BUILDER");
    }
}
