package defpackage;

/* compiled from: r8-map-id-39a5fd6059330804833c2374f28b82f3b8aef423af32ebd824babcd2cdcd11b4 */
/* loaded from: classes.dex */
public final class Dg0 implements Cg0 {
    public static final C1318ge0 A;
    public static final C1318ge0 B;
    public static final C1318ge0 C;
    public static final C1318ge0 D;
    public static final C1318ge0 E;
    public static final C1318ge0 F;
    public static final C1318ge0 G;
    public static final C1318ge0 H;
    public static final C1318ge0 I;
    public static final C1318ge0 J;
    public static final C1318ge0 K;
    public static final C1318ge0 L;
    public static final C1318ge0 M;
    public static final C1318ge0 N;
    public static final C1318ge0 O;
    public static final C1318ge0 P;
    public static final C1318ge0 Q;
    public static final C1318ge0 R;
    public static final C1318ge0 S;
    public static final C1318ge0 T;
    public static final C1318ge0 U;
    public static final C1318ge0 V;
    public static final C1318ge0 W;
    public static final C1318ge0 X;
    public static final C1318ge0 Y;
    public static final C1318ge0 Z;
    public static final C1318ge0 a;
    public static final C1318ge0 a0;
    public static final C1318ge0 b;
    public static final C1318ge0 b0;
    public static final C1318ge0 c;
    public static final C1318ge0 c0;
    public static final C1318ge0 d;
    public static final C1318ge0 d0;
    public static final C1318ge0 e;
    public static final C1318ge0 e0;
    public static final C1318ge0 f;
    public static final C1318ge0 f0;
    public static final C1318ge0 g;
    public static final C1318ge0 g0;
    public static final C1318ge0 h;
    public static final C1318ge0 h0;
    public static final C1318ge0 i;
    public static final C1318ge0 i0;
    public static final C1318ge0 j;
    public static final C1318ge0 j0;
    public static final C1318ge0 k;
    public static final C1318ge0 k0;
    public static final C1318ge0 l;
    public static final C1318ge0 l0;
    public static final C1318ge0 m;
    public static final C1318ge0 m0;
    public static final C1318ge0 n;
    public static final C1318ge0 n0;
    public static final C1318ge0 o;
    public static final C1318ge0 o0;
    public static final C1318ge0 p;
    public static final C1318ge0 p0;
    public static final C1318ge0 q;
    public static final C1318ge0 q0;
    public static final C1318ge0 r;
    public static final C1318ge0 r0;
    public static final C1318ge0 s;
    public static final C1318ge0 s0;
    public static final C1318ge0 t;
    public static final C1318ge0 t0;
    public static final C1318ge0 u;
    public static final C1318ge0 v;
    public static final C1318ge0 w;
    public static final C1318ge0 x;
    public static final C1318ge0 y;
    public static final C1318ge0 z;

    static {
        I9 i9 = new I9(AbstractC0887be0.a(), true, true);
        a = i9.h("measurement.ad_id_cache_time", 10000L);
        b = i9.h("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L);
        c = i9.j("measurement.config.bundle_for_all_apps_on_backgrounded", true);
        d = i9.h("measurement.max_bundles_per_iteration", 100L);
        e = i9.h("measurement.config.cache_time", 86400000L);
        i9.i("measurement.log_tag", "FA");
        f = i9.i("measurement.config.url_authority", "app-measurement.com");
        g = i9.i("measurement.config.url_scheme", "https");
        h = i9.h("measurement.upload.debug_upload_interval", 1000L);
        i = i9.h("measurement.session.engagement_interval", 3600000L);
        j = i9.i("measurement.rb.attribution.event_params", "value|currency");
        k = i9.h("measurement.upload.google_signal_max_queue_time", 605000L);
        l = i9.i("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d");
        m = i9.h("measurement.lifetimevalue.max_currency_tracked", 4L);
        n = i9.h("measurement.dma_consent.max_daily_dcu_realtime_events", 1L);
        o = i9.h("measurement.upload.max_event_parameter_value_length", 500L);
        p = i9.h("measurement.store.max_stored_events_per_app", 100000L);
        q = i9.h("measurement.experiment.max_ids", 50L);
        r = i9.h("measurement.audience.filter_result_max_count", 200L);
        s = i9.h("measurement.upload.max_item_scoped_custom_parameters", 27L);
        t = i9.h("measurement.rb.max_trigger_registrations_per_day", 1000L);
        u = i9.h("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0L);
        v = i9.h("measurement.rb.attribution.client.min_ad_services_version", 7L);
        w = i9.h("measurement.alarm_manager.minimum_interval", 60000L);
        x = i9.h("measurement.upload.minimum_delay", 500L);
        y = i9.h("measurement.monitoring.sample_period_millis", 86400000L);
        z = i9.h("measurement.rb.attribution.notify_app_delay_millis", 3000L);
        A = i9.j("measurement.config.notify_trigger_uris_on_backgrounded", true);
        B = i9.i("measurement.rb.attribution.app_allowlist", "*");
        C = i9.h("measurement.upload.realtime_upload_interval", 10000L);
        D = i9.h("measurement.upload.refresh_blacklisted_config_interval", 604800000L);
        i9.h("measurement.config.cache_time.service", 3600000L);
        E = i9.h("measurement.service_client.idle_disconnect_millis", 5000L);
        i9.i("measurement.log_tag.service", "FA-SVC");
        F = i9.h("measurement.service_client.reconnect_millis", 1000L);
        i9.i("measurement.sgtm.app_allowlist", "*");
        G = i9.h("measurement.sgtm.batch.retry_interval", 1800000L);
        H = i9.h("measurement.sgtm.batch.retry_max_count", 10L);
        I = i9.h("measurement.sgtm.batch.retry_max_wait", 21600000L);
        J = i9.i("measurement.sgtm.service_upload_apps_list", "");
        K = i9.i("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504");
        L = i9.h("measurement.sgtm.upload.batches_retrieval_limit", 5L);
        M = i9.h("measurement.sgtm.upload.max_queued_batches", 5000L);
        N = i9.h("measurement.sgtm.upload.min_delay_after_background", 600000L);
        O = i9.h("measurement.sgtm.upload.min_delay_after_broadcast", 1000L);
        P = i9.h("measurement.sgtm.upload.min_delay_after_startup", 5000L);
        Q = i9.h("measurement.sgtm.upload.retry_interval", 600000L);
        R = i9.h("measurement.sgtm.upload.retry_max_wait", 21600000L);
        S = i9.h("measurement.upload.stale_data_deletion_interval", 86400000L);
        T = i9.h("measurement.rb.attribution.max_retry_delay_seconds", 16L);
        U = i9.h("measurement.rb.attribution.client.min_time_after_boot_seconds", 90L);
        V = i9.i("measurement.rb.attribution.uri_authority", "google-analytics.com");
        W = i9.h("measurement.rb.attribution.max_queue_time", 864000000L);
        X = i9.i("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion");
        Y = i9.i("measurement.rb.attribution.query_parameters_to_remove", "");
        Z = i9.i("measurement.rb.attribution.uri_scheme", "https");
        a0 = i9.h("measurement.sdk.attribution.cache.ttl", 604800000L);
        b0 = i9.h("measurement.redaction.app_instance_id.ttl", 7200000L);
        c0 = i9.h("measurement.upload.backoff_period", 43200000L);
        d0 = i9.h("measurement.upload.initial_upload_delay_time", 15000L);
        e0 = i9.h("measurement.upload.interval", 3600000L);
        f0 = i9.h("measurement.upload.max_bundle_size", 65536L);
        g0 = i9.h("measurement.upload.max_bundles", 100L);
        h0 = i9.h("measurement.upload.max_conversions_per_day", 500L);
        i0 = i9.h("measurement.upload.max_error_events_per_day", 1000L);
        j0 = i9.h("measurement.upload.max_events_per_bundle", 1000L);
        k0 = i9.h("measurement.upload.max_events_per_day", 100000L);
        l0 = i9.h("measurement.upload.max_public_events_per_day", 50000L);
        m0 = i9.h("measurement.upload.max_queue_time", 518400000L);
        n0 = i9.h("measurement.upload.max_realtime_events_per_day", 10L);
        o0 = i9.h("measurement.upload.max_batch_size", 65536L);
        p0 = i9.h("measurement.upload.retry_count", 6L);
        q0 = i9.h("measurement.upload.retry_time", 1800000L);
        r0 = i9.i("measurement.upload.url", "https://app-measurement.com/a");
        s0 = i9.h("measurement.upload.window_interval", 3600000L);
        t0 = i9.i("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot");
    }
}
