package com.applovin.impl.sdk.c;

import com.applovin.impl.sdk.utils.AppLovinSdkExtraParameterKey;
import com.applovin.impl.sdk.utils.u;
import defpackage.BC;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;

/* compiled from: r8-map-id-39a5fd6059330804833c2374f28b82f3b8aef423af32ebd824babcd2cdcd11b4 */
/* loaded from: classes.dex */
public class a<T> extends b<T> {
    public static final b<Long> aJA;
    public static final b<Long> aJB;
    public static final b<Boolean> aJC;
    public static final b<Boolean> aJD;
    public static final b<Boolean> aJE;
    public static final b<Boolean> aJF;
    public static final b<Long> aJG;
    public static final b<Long> aJH;
    public static final b<Long> aJI;
    public static final b<Boolean> aJJ;
    public static final b<Boolean> aJK;
    public static final b<Long> aJL;
    public static final b<Long> aJM;
    public static final b<Long> aJN;
    public static final b<Boolean> aJO;
    public static final b<Boolean> aJP;
    public static final b<Long> aJQ;
    public static final b<Boolean> aJR;
    public static final b<Integer> aJS;
    public static final b<String> aJT;
    public static final b<String> aJU;
    public static final b<Integer> aJV;
    public static final b<String> aJW;
    public static final b<Boolean> aJX;
    public static final b<Boolean> aJY;
    public static final b<Boolean> aJZ;
    public static final b<String> aJe = b.d("afi", "");
    public static final b<Long> aJf;
    public static final b<String> aJg;
    public static final b<String> aJh;
    public static final b<Long> aJi;
    public static final b<Long> aJj;
    public static final b<Long> aJk;
    public static final b<Boolean> aJl;
    public static final b<String> aJm;
    public static final b<Long> aJn;
    public static final b<Long> aJo;
    public static final b<Long> aJp;
    public static final b<Long> aJq;
    public static final b<String> aJr;
    public static final b<Long> aJs;
    public static final b<Boolean> aJt;
    public static final b<Boolean> aJu;
    public static final b<Boolean> aJv;
    public static final b<Boolean> aJw;
    public static final b<Boolean> aJx;
    public static final b<Long> aJy;
    public static final b<Boolean> aJz;
    public static final b<Boolean> aKa;
    public static final b<String> aKb;
    public static final b<Long> aKc;
    public static final b<Long> aKd;
    public static final b<Long> aKe;
    public static final b<Boolean> aKf;
    public static final b<Boolean> aKg;

    static {
        TimeUnit timeUnit = TimeUnit.SECONDS;
        aJf = BC.g(timeUnit, 5L, "afi_ms");
        aJg = b.d("mediation_endpoint", "https://ms.applovin.com/");
        aJh = b.d("mediation_backup_endpoint", "https://ms.applvn.com/");
        aJi = BC.g(timeUnit, 2L, "fetch_next_ad_retry_delay_ms");
        aJj = BC.g(timeUnit, 30L, "fetch_next_ad_timeout_ms");
        aJk = BC.g(timeUnit, 7L, "fetch_mediation_debugger_info_timeout_ms");
        Boolean bool = Boolean.TRUE;
        aJl = b.d("auto_init_mediation_debugger", bool);
        aJm = b.d("postback_macros", "{\"{MCODE}\":\"mcode\",\"{BCODE}\":\"bcode\",\"{ICODE}\":\"icode\",\"{SCODE}\":\"scode\"}");
        aJn = BC.g(timeUnit, 30L, "max_signal_provider_latency_ms");
        aJo = BC.g(timeUnit, 10L, "default_adapter_timeout_ms");
        aJp = BC.g(timeUnit, 30L, "ad_refresh_ms");
        aJq = BC.g(timeUnit, 30L, "ad_load_failure_refresh_ms");
        aJr = b.d("ad_load_failure_refresh_ignore_error_codes", "204");
        aJs = b.d("refresh_ad_on_app_resume_elapsed_threshold_ms", 0L);
        aJt = b.d("refresh_ad_view_timer_responds_to_background", bool);
        aJu = b.d("refresh_ad_view_timer_responds_to_store_kit", bool);
        Boolean bool2 = Boolean.FALSE;
        aJv = b.d("refresh_ad_view_timer_responds_to_window_visibility_changed", bool2);
        aJw = b.d("avrsponse", bool2);
        aJx = b.d(AppLovinSdkExtraParameterKey.ALLOW_IMMEDIATE_AUTO_REFRESH_PAUSE, bool2);
        aJy = b.d("fullscreen_display_delay_ms", 0L);
        aJz = b.d("susaode", bool2);
        aJA = b.d("ahdm", 500L);
        aJB = b.d("ad_view_refresh_precache_request_viewability_undesired_flags", 246L);
        aJC = b.d("ad_view_refresh_precache_request_enabled", bool);
        aJD = b.d("ssvaal", bool2);
        aJE = b.d("fabsina", bool2);
        aJF = b.d("fabsiaif", bool2);
        aJG = b.d("famttl_ms", 0L);
        TimeUnit timeUnit2 = TimeUnit.HOURS;
        aJH = BC.g(timeUnit2, 4L, "ad_expiration_ms");
        aJI = BC.g(timeUnit2, 4L, "native_ad_expiration_ms");
        aJJ = b.d("rena", bool);
        aJK = b.d("native_downscale_icon_fix", bool2);
        aJL = b.d("fullscreen_ad_displayed_timeout_ms", -1L);
        aJM = b.d("freast_ms", -1L);
        aJN = b.d("ad_hidden_timeout_ms", -1L);
        aJO = b.d("schedule_ad_hidden_on_ad_dismiss", bool2);
        aJP = b.d("schedule_ad_hidden_on_single_task_app_relaunch", bool2);
        aJQ = BC.g(timeUnit, 1L, "ad_hidden_on_ad_dismiss_callback_delay_ms");
        aJR = b.d("proe", bool2);
        aJS = b.d("mute_state", 2);
        aJT = b.d("saf", "");
        aJU = b.d("saui", "");
        aJV = b.d("mra", -1);
        aJW = b.d("mra_af", "INTER,REWARDED,REWARDED_INTER,BANNER,LEADER,MREC");
        aJX = b.d("fadiafase", bool);
        aJY = b.d("fadwvcv", bool);
        aJZ = b.d("bfarud", bool2);
        aKa = b.d("inacc", Boolean.valueOf(u.N((List<String>) Arrays.asList("com.textmeinc.textme", "com.textmeinc.freetone", "com.textmeinc.textme3", "com.jaumo", "com.jaumo.casual", "com.pinkapp", "com.jaumo.mature", "com.jaumo.prime", "com.jaumo.gay", "com.jaumo.lesbian"))));
        aKb = b.d("pbataipaf", "");
        aKc = BC.g(timeUnit, 30L, "bwt_ms");
        aKd = BC.g(timeUnit, 30L, "twt_ms");
        aKe = b.d("adiets_sec", Long.valueOf(TimeUnit.MINUTES.toSeconds(1L)));
        aKf = b.d("fetch_mediated_ad_gzip", bool);
        aKg = b.d("max_postback_gzip", bool);
    }
}
