package com.applovin.impl.sdk.c;

import android.net.Uri;
import com.applovin.impl.adview.AppLovinTouchToClickListener;
import com.applovin.impl.b.n;
import com.applovin.impl.sdk.utils.AppLovinSdkExtraParameterKey;
import com.applovin.impl.sdk.utils.p;
import com.applovin.mediation.MaxAdFormat;
import com.applovin.sdk.AppLovinAdSize;
import com.applovin.sdk.AppLovinMediationProvider;
import com.facebook.imageutils.JfifUtil;
import defpackage.AbstractC2612wf;
import defpackage.BC;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

/* compiled from: r8-map-id-39a5fd6059330804833c2374f28b82f3b8aef423af32ebd824babcd2cdcd11b4 */
/* loaded from: classes.dex */
public class b<T> implements Comparable {
    public static final b<Boolean> aKA;
    public static final b<Integer> aKB;
    public static final b<Integer> aKC;
    public static final b<Integer> aKD;
    public static final b<Boolean> aKE;
    public static final b<Boolean> aKF;
    public static final b<Boolean> aKG;
    public static final b<Boolean> aKH;
    public static final b<Boolean> aKI;
    public static final b<Integer> aKJ;
    public static final b<String> aKK;
    public static final b<Boolean> aKL;
    public static final b<String> aKM;
    public static final b<Boolean> aKN;
    public static final b<Boolean> aKO;
    public static final b<Boolean> aKP;
    public static final b<Boolean> aKQ;
    public static final b<String> aKR;
    public static final b<Boolean> aKS;
    public static final b<String> aKT;
    public static final b<Boolean> aKU;
    public static final b<Long> aKV;
    public static final b<Boolean> aKW;
    public static final b<Boolean> aKX;
    public static final b<Boolean> aKY;
    public static final b<Boolean> aKZ;
    private static final List<?> aKh = Arrays.asList(Boolean.class, Float.class, Integer.class, Long.class, String.class);
    private static final Map<String, b<?>> aKi = new HashMap(512);
    public static final b<Boolean> aKk;
    public static final b<String> aKl;
    public static final b<Boolean> aKm;
    public static final b<Boolean> aKn;
    public static final b<String> aKo;
    public static final b<Long> aKp;
    public static final b<Boolean> aKq;
    public static final b<String> aKr;
    public static final b<String> aKs;
    public static final b<String> aKt;
    public static final b<String> aKu;
    public static final b<Boolean> aKv;
    public static final b<Boolean> aKw;
    public static final b<Long> aKx;
    public static final b<Integer> aKy;
    public static final b<Integer> aKz;
    public static final b<String> aLA;
    public static final b<String> aLB;
    public static final b<String> aLC;
    public static final b<String> aLD;
    public static final b<Boolean> aLE;
    public static final b<Integer> aLF;
    public static final b<Integer> aLG;
    public static final b<Boolean> aLH;
    public static final b<Boolean> aLI;
    public static final b<Long> aLJ;
    public static final b<Integer> aLK;
    public static final b<String> aLL;
    public static final b<Boolean> aLM;
    public static final b<String> aLN;
    public static final b<String> aLO;
    public static final b<Integer> aLP;
    public static final b<Boolean> aLQ;
    public static final b<Integer> aLR;
    public static final b<Integer> aLS;
    public static final b<Boolean> aLT;
    public static final b<Boolean> aLU;
    public static final b<Boolean> aLV;
    public static final b<Boolean> aLW;
    public static final b<Boolean> aLX;
    public static final b<Boolean> aLY;
    public static final b<Boolean> aLZ;
    public static final b<Long> aLa;
    public static final b<Long> aLb;
    public static final b<Long> aLc;
    public static final b<Long> aLd;
    public static final b<Long> aLe;
    public static final b<Long> aLf;
    public static final b<String> aLg;
    public static final b<String> aLh;
    public static final b<String> aLi;
    public static final b<String> aLj;
    public static final b<Long> aLk;
    public static final b<Integer> aLl;
    public static final b<Integer> aLm;
    public static final b<Integer> aLn;
    public static final b<Integer> aLo;
    public static final b<Integer> aLp;
    public static final b<Integer> aLq;
    public static final b<String> aLr;
    public static final b<String> aLs;
    public static final b<String> aLt;
    public static final b<String> aLu;
    public static final b<String> aLv;
    public static final b<String> aLw;
    public static final b<String> aLx;
    public static final b<String> aLy;
    public static final b<String> aLz;
    public static final b<Integer> aMA;
    public static final b<Float> aMB;
    public static final b<Long> aMC;
    public static final b<Long> aMD;
    public static final b<Integer> aME;
    public static final b<Integer> aMF;
    public static final b<Integer> aMG;
    public static final b<Boolean> aMH;
    public static final b<Integer> aMI;
    public static final b<Boolean> aMJ;
    public static final b<String> aMK;
    public static final b<String> aML;
    public static final b<String> aMM;
    public static final b<Integer> aMN;
    public static final b<Long> aMO;
    public static final b<Long> aMP;
    public static final b<Boolean> aMQ;
    public static final b<Integer> aMR;
    public static final b<Integer> aMS;
    public static final b<Integer> aMT;
    public static final b<Integer> aMU;
    public static final b<Integer> aMV;
    public static final b<Integer> aMW;
    public static final b<Integer> aMX;
    public static final b<Integer> aMY;
    public static final b<Boolean> aMZ;
    public static final b<Boolean> aMa;
    public static final b<Boolean> aMb;
    public static final b<Boolean> aMc;
    public static final b<Long> aMd;
    public static final b<Boolean> aMe;
    public static final b<Integer> aMf;
    public static final b<Integer> aMg;
    public static final b<String> aMh;
    public static final b<String> aMi;
    public static final b<String> aMj;
    public static final b<String> aMk;
    public static final b<String> aMl;
    public static final b<String> aMm;
    public static final b<String> aMn;
    public static final b<String> aMo;
    public static final b<Integer> aMp;
    public static final b<Integer> aMq;
    public static final b<Boolean> aMr;
    public static final b<Long> aMs;
    public static final b<Integer> aMt;
    public static final b<Integer> aMu;
    public static final b<Integer> aMv;
    public static final b<Integer> aMw;
    public static final b<Integer> aMx;
    public static final b<Integer> aMy;
    public static final b<Integer> aMz;
    public static final b<Boolean> aNA;
    public static final b<Boolean> aNB;
    public static final b<Integer> aNC;
    public static final b<Integer> aND;
    public static final b<Integer> aNE;
    public static final b<Integer> aNF;
    public static final b<Integer> aNG;
    public static final b<Boolean> aNH;
    public static final b<Boolean> aNI;
    public static final b<Boolean> aNJ;
    public static final b<Integer> aNK;
    public static final b<Integer> aNL;
    public static final b<Integer> aNM;
    public static final b<Boolean> aNN;
    public static final b<Integer> aNO;
    public static final b<Integer> aNP;
    public static final b<Boolean> aNQ;
    public static final b<Boolean> aNR;
    public static final b<Integer> aNS;
    public static final b<Integer> aNT;
    public static final b<Integer> aNU;
    public static final b<Integer> aNV;
    public static final b<Boolean> aNW;
    public static final b<Boolean> aNX;
    public static final b<Integer> aNY;
    public static final b<Boolean> aNZ;
    public static final b<Long> aNa;
    public static final b<Long> aNb;
    public static final b<Boolean> aNc;
    public static final b<Boolean> aNd;
    public static final b<Boolean> aNe;
    public static final b<Boolean> aNf;
    public static final b<Boolean> aNg;
    public static final b<Boolean> aNh;
    public static final b<Boolean> aNi;
    public static final b<Integer> aNj;
    public static final b<Integer> aNk;
    public static final b<Integer> aNl;
    public static final b<Long> aNm;
    public static final b<Integer> aNn;
    public static final b<Integer> aNo;
    public static final b<Integer> aNp;
    public static final b<Boolean> aNq;
    public static final b<Long> aNr;
    public static final b<Boolean> aNs;
    public static final b<Boolean> aNt;
    public static final b<Boolean> aNu;
    public static final b<Long> aNv;
    public static final b<Boolean> aNw;
    public static final b<Integer> aNx;
    public static final b<Integer> aNy;
    public static final b<Boolean> aNz;
    public static final b<Boolean> aOA;
    public static final b<Boolean> aOB;
    public static final b<Boolean> aOC;
    public static final b<String> aOD;
    public static final b<Boolean> aOE;
    public static final b<Boolean> aOF;
    public static final b<Boolean> aOG;
    public static final b<Boolean> aOH;
    public static final b<Boolean> aOI;
    public static final b<Boolean> aOJ;
    public static final b<Boolean> aOK;
    public static final b<Boolean> aOL;
    public static final b<Boolean> aOM;
    public static final b<Boolean> aON;
    public static final b<Boolean> aOO;
    public static final b<Boolean> aOP;
    public static final b<Float> aOQ;
    public static final b<Boolean> aOR;
    public static final b<Boolean> aOS;
    public static final b<Boolean> aOT;
    public static final b<Boolean> aOU;
    public static final b<Boolean> aOV;
    public static final b<Float> aOW;
    public static final b<Integer> aOX;
    public static final b<Boolean> aOY;
    public static final b<Integer> aOZ;
    public static final b<Boolean> aOa;
    public static final b<Boolean> aOb;
    public static final b<Long> aOc;
    public static final b<Integer> aOd;
    public static final b<Long> aOe;
    public static final b<Long> aOf;
    public static final b<Long> aOg;
    public static final b<Boolean> aOh;
    public static final b<Boolean> aOi;
    public static final b<Long> aOj;
    public static final b<Integer> aOk;
    public static final b<Boolean> aOl;
    public static final b<Long> aOm;
    public static final b<Long> aOn;
    public static final b<Boolean> aOo;
    public static final b<Boolean> aOp;
    public static final b<Boolean> aOq;
    public static final b<Boolean> aOr;
    public static final b<Boolean> aOs;
    public static final b<Boolean> aOt;
    public static final b<Boolean> aOu;
    public static final b<Boolean> aOv;
    public static final b<Boolean> aOw;
    public static final b<Boolean> aOx;
    public static final b<Boolean> aOy;
    public static final b<Boolean> aOz;
    public static final b<Integer> aPA;
    public static final b<Integer> aPB;
    public static final b<Integer> aPC;
    public static final b<Integer> aPD;
    public static final b<Integer> aPE;
    public static final b<Float> aPF;
    public static final b<Boolean> aPG;
    public static final b<Boolean> aPH;
    public static final b<Integer> aPI;
    public static final b<Boolean> aPJ;
    public static final b<String> aPK;
    public static final b<Boolean> aPL;
    public static final b<Integer> aPM;
    public static final b<Boolean> aPN;
    public static final b<Integer> aPO;
    public static final b<Boolean> aPP;
    public static final b<Integer> aPQ;
    public static final b<Integer> aPR;
    public static final b<Integer> aPS;
    public static final b<Integer> aPT;
    public static final b<Integer> aPU;
    public static final b<Integer> aPV;
    public static final b<Integer> aPW;
    public static final b<Integer> aPX;
    public static final b<Boolean> aPY;
    public static final b<Boolean> aPZ;
    public static final b<String> aPa;
    public static final b<Integer> aPb;
    public static final b<String> aPc;
    public static final b<Boolean> aPd;
    public static final b<Integer> aPe;
    public static final b<Integer> aPf;
    public static final b<Integer> aPg;
    public static final b<Integer> aPh;
    public static final b<Integer> aPi;
    public static final b<Integer> aPj;
    public static final b<Boolean> aPk;
    public static final b<Long> aPl;
    public static final b<Integer> aPm;
    public static final b<Boolean> aPn;
    public static final b<Integer> aPo;
    public static final b<String> aPp;
    public static final b<String> aPq;
    public static final b<Integer> aPr;
    public static final b<Integer> aPs;
    public static final b<String> aPt;
    public static final b<String> aPu;
    public static final b<Boolean> aPv;
    public static final b<Integer> aPw;
    public static final b<Integer> aPx;
    public static final b<Integer> aPy;
    public static final b<Integer> aPz;
    public static final b<Boolean> aQA;
    public static final b<Long> aQB;
    public static final b<Long> aQC;
    public static final b<Integer> aQD;
    public static final b<Integer> aQE;
    public static final b<Boolean> aQF;
    public static final b<Boolean> aQG;
    public static final b<Boolean> aQH;
    public static final b<Boolean> aQI;
    public static final b<Integer> aQJ;
    public static final b<Integer> aQK;
    public static final b<Boolean> aQL;
    public static final b<Boolean> aQM;
    public static final b<Boolean> aQN;
    public static final b<Boolean> aQO;
    public static final b<Boolean> aQP;
    public static final b<Boolean> aQQ;
    public static final b<Boolean> aQR;
    public static final b<Boolean> aQS;
    public static final b<String> aQT;
    public static final b<String> aQU;
    public static final b<String> aQV;
    public static final b<String> aQW;
    public static final b<Integer> aQX;
    public static final b<Boolean> aQY;
    public static final b<Long> aQZ;
    public static final b<Boolean> aQa;
    public static final b<Boolean> aQb;
    public static final b<Boolean> aQc;
    public static final b<Boolean> aQd;
    public static final b<Boolean> aQe;
    public static final b<Boolean> aQf;
    public static final b<Long> aQg;
    public static final b<Long> aQh;
    public static final b<Integer> aQi;
    public static final b<Boolean> aQj;
    public static final b<Boolean> aQk;
    public static final b<Boolean> aQl;
    public static final b<Boolean> aQm;
    public static final b<Boolean> aQn;
    public static final b<Boolean> aQo;
    public static final b<Boolean> aQp;
    public static final b<Boolean> aQq;
    public static final b<Boolean> aQr;
    public static final b<Boolean> aQs;
    public static final b<Boolean> aQt;
    public static final b<Boolean> aQu;
    public static final b<Boolean> aQv;
    public static final b<Long> aQw;
    public static final b<Long> aQx;
    public static final b<Long> aQy;
    public static final b<Boolean> aQz;
    public static final b<Long> aRa;
    public static final b<Boolean> aRb;
    public static final b<Boolean> aRc;
    public static final b<Boolean> aRd;
    public static final b<Boolean> aRe;
    private final T aKj;
    private final String name;

    static {
        Boolean bool = Boolean.FALSE;
        aKk = d("is_disabled", bool);
        aKl = d("device_id", "");
        Boolean bool2 = Boolean.TRUE;
        aKm = d("rss", bool2);
        aKn = d("rssoitf", bool);
        aKo = d("device_token", "");
        aKp = d("publisher_id", 0L);
        aKq = d("is_verbose_logging", bool);
        aKr = d("sc", "");
        aKs = d("sc2", "");
        aKt = d("sc3", "");
        aKu = d("server_installed_at", "");
        aKv = d("pnrc", bool);
        aKw = d("clear_completion_callback_on_failure", bool);
        aKx = d("sicd_ms", 0L);
        aKy = d("logcat_max_line_size", 1000);
        aKz = d("stps", 2);
        aKA = d("exception_handler_enabled", bool2);
        aKB = d("network_thread_count", 2);
        aKC = d("aei", -1);
        aKD = d("mei", -1);
        aKE = d("bdae", bool);
        aKF = d("tewllm", bool2);
        aKG = d("lisvib", bool);
        aKH = d("tewplosda", bool2);
        aKI = d("srwbe", bool);
        aKJ = d("malaera", -1);
        aKK = d("eralaf", "");
        aKL = d("eraziie", bool);
        aKM = d("ps_atu", "");
        aKN = d("ah_cvc", bool2);
        aKO = d("ah_cdde", bool2);
        aKP = d("ah_crut", bool2);
        aKQ = d("init_omsdk", bool2);
        aKR = d("omsdk_partner_name", "applovin");
        aKS = d("publisher_can_show_consent_dialog", bool2);
        aKT = d("consent_dialog_url", "https://assets.applovin.com/gdpr/flow_v1/gdpr-flow-1.html");
        aKU = d("consent_dialog_immersive_mode_on", bool);
        aKV = d("consent_dialog_show_from_alert_delay_ms", 450L);
        aKW = d("alert_consent_for_dialog_rejected", bool);
        aKX = d("alert_consent_for_dialog_closed", bool);
        aKY = d("alert_consent_for_dialog_closed_with_back_button", bool);
        aKZ = d("alert_consent_after_init", bool);
        TimeUnit timeUnit = TimeUnit.MINUTES;
        aLa = BC.g(timeUnit, 5L, "alert_consent_after_init_interval_ms");
        aLb = BC.g(timeUnit, 30L, "alert_consent_after_dialog_rejection_interval_ms");
        aLc = BC.g(timeUnit, 5L, "alert_consent_after_dialog_close_interval_ms");
        aLd = BC.g(timeUnit, 5L, "alert_consent_after_dialog_close_with_back_button_interval_ms");
        aLe = BC.g(timeUnit, 10L, "alert_consent_after_cancel_interval_ms");
        aLf = BC.g(timeUnit, 5L, "alert_consent_reschedule_interval_ms");
        aLg = d("text_alert_consent_title", "Make this App Better and Stay Free!");
        aLh = d("text_alert_consent_body", "If you don't give us consent to use your data, you will be making our ability to support this app harder, which may negatively affect the user experience.");
        aLi = d("text_alert_consent_yes_option", "I Agree");
        aLj = d("text_alert_consent_no_option", "Cancel");
        TimeUnit timeUnit2 = TimeUnit.SECONDS;
        aLk = BC.g(timeUnit2, 1L, "ttc_max_click_duration_ms");
        aLl = d("ttc_max_click_distance_dp", 10);
        AppLovinTouchToClickListener.ClickRecognitionState clickRecognitionState = AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN;
        aLm = d("ttc_acrsv2a", Integer.valueOf(clickRecognitionState.ordinal()));
        aLn = d("ttc_acrsnv", Integer.valueOf(clickRecognitionState.ordinal()));
        aLo = d("ttc_acrsa", Integer.valueOf(clickRecognitionState.ordinal()));
        aLp = d("ttc_acrsn", Integer.valueOf(clickRecognitionState.ordinal()));
        aLq = d("ttc_edge_buffer_dp", 0);
        aLr = d("whitelisted_postback_endpoints", "https://prod-a.applovin.com,https://rt.applovin.com/4.0/pix, https://rt.applvn.com/4.0/pix,https://ms.applovin.com/,https://ms.applvn.com/");
        aLs = d("fetch_settings_endpoint", "https://ms.applovin.com/");
        aLt = d("fetch_settings_backup_endpoint", "https://ms.applvn.com/");
        aLu = d("adserver_endpoint", "https://a.applovin.com/");
        aLv = d("adserver_backup_endpoint", "https://a.applvn.com/");
        aLw = d("api_endpoint", "https://d.applovin.com/");
        aLx = d("api_backup_endpoint", "https://d.applvn.com/");
        aLy = d("event_tracking_endpoint_v2", "https://rt.applovin.com/");
        aLz = d("event_tracking_backup_endpoint_v2", "https://rt.applvn.com/");
        aLA = d("token_type_prefixes_r", "4!");
        aLB = d("token_type_prefixes_arj", "json_v3!");
        aLC = d("top_level_events", "landing,paused,resumed,cf_start,tos_ok,gdpr_ok,ref,rdf,checkout,iap");
        aLD = d("valid_super_property_types", String.class.getName() + "," + Integer.class.getName() + "," + Long.class.getName() + "," + Double.class.getName() + "," + Float.class.getName() + "," + Date.class.getName() + "," + Uri.class.getName() + "," + List.class.getName() + "," + Map.class.getName());
        aLE = d("persist_super_properties", bool2);
        aLF = d("super_property_string_max_length", 1024);
        aLG = d("super_property_url_max_length", 1024);
        aLH = d("use_per_format_cache_queues", bool2);
        aLI = d("cache_cleanup_enabled", bool);
        TimeUnit timeUnit3 = TimeUnit.DAYS;
        aLJ = d("cache_file_ttl_seconds", Long.valueOf(timeUnit3.toSeconds(1L)));
        aLK = d("cache_max_size_mb", -1);
        aLL = d("precache_delimiters", ")]', ");
        aLM = d("ad_resource_caching_enabled", bool2);
        aLN = d("resource_cache_prefix", "https://vid.applovin.com/,https://stage-vid.applovin.com/,https://pdn.applovin.com/,https://stage-pdn.applovin.com/,https://img.applovin.com/,https://stage-img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://stage-assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://stage-vid.applovin.com/,http://pdn.applovin.com/,http://stage-pdn.applovin.com/,http://img.applovin.com/,http://stage-img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://stage-assets.applovin.com/,http://cdnjs.cloudflare.com/,http://u.appl.vn/,https://u.appl.vn/,https://res.applovin.com/,https://res1.applovin.com/,https://res2.applovin.com/,https://res3.applovin.com/,http://res.applovin.com/,http://res1.applovin.com/,http://res2.applovin.com/,http://res3.applovin.com/");
        aLO = d("preserved_cached_assets", "sound_off.png,sound_on.png,closeOptOut.png,1381250003_28x28.png,zepto-1.1.3.min.js,jquery-2.1.1.min.js,jquery-1.9.1.min.js,jquery.knob.js");
        aLP = d("resource_max_filename_length", Integer.valueOf(JfifUtil.MARKER_FIRST_BYTE));
        aLQ = d("ccrc", bool);
        aLR = d("mcct", 3);
        aLS = d("mchct", 3);
        aLT = d("dficf", bool);
        aLU = d("decr", bool);
        aLV = d("dcrome", bool);
        aLW = d("dcrobs", bool);
        aLX = d("upcan", bool);
        aLY = d("ugfnfhr", bool);
        aLZ = d("lfeufc", bool);
        aMa = d("pcro", bool);
        aMb = d("efecobt", bool);
        aMc = d("saewib", bool);
        aMd = d("fsae_ms", -1L);
        aMe = d("raae", bool);
        aMf = d("vr_retry_count_v1", 1);
        aMg = d("cr_retry_count_v1", 1);
        aMh = d("text_incent_warning_title", "Attention!");
        aMi = d("text_incent_warning_body", "You won’t get your reward if the video hasn’t finished.");
        aMj = d("text_incent_warning_close_option", "Close");
        aMk = d("text_incent_warning_continue_option", "Keep Watching");
        aMl = d("text_incent_nonvideo_warning_title", "Attention!");
        aMm = d("text_incent_nonvideo_warning_body", "You won’t get your reward if the game hasn’t finished.");
        aMn = d("text_incent_nonvideo_warning_close_option", "Close");
        aMo = d("text_incent_nonvideo_warning_continue_option", "Keep Playing");
        aMp = d("close_button_touch_area", 0);
        aMq = d("close_button_outside_touch_area", 0);
        aMr = d("creative_debugger_enabled", bool2);
        aMs = BC.g(timeUnit2, 1L, "viewability_adview_imp_delay_ms");
        aMt = d("viewability_adview_banner_min_width", 320);
        aMu = d("viewability_adview_banner_min_height", Integer.valueOf(AppLovinAdSize.BANNER.getHeight()));
        MaxAdFormat maxAdFormat = MaxAdFormat.MREC;
        aMv = d("viewability_adview_mrec_min_width", Integer.valueOf(maxAdFormat.getSize().getWidth()));
        aMw = d("viewability_adview_mrec_min_height", Integer.valueOf(maxAdFormat.getSize().getHeight()));
        aMx = d("viewability_adview_leader_min_width", 728);
        aMy = d("viewability_adview_leader_min_height", Integer.valueOf(AppLovinAdSize.LEADER.getHeight()));
        aMz = d("viewability_adview_native_min_width", 0);
        aMA = d("viewability_adview_native_min_height", 0);
        aMB = d("viewability_adview_min_alpha", Float.valueOf(10.0f));
        aMC = BC.g(timeUnit2, 1L, "viewability_timer_min_visible_ms");
        aMD = d("viewability_timer_interval_ms", 100L);
        aME = d("expandable_close_button_size", 27);
        aMF = d("expandable_h_close_button_margin", 10);
        aMG = d("expandable_t_close_button_margin", 10);
        aMH = d("expandable_lhs_close_button", bool);
        aMI = d("expandable_close_button_touch_area", 0);
        aMJ = d("iaad", bool);
        aMK = d("js_tag_schemes", "applovin,mopub");
        aML = d("js_tag_load_success_hosts", "load,load_succeeded");
        aMM = d("js_tag_load_failure_hosts", "failLoad,load_failed");
        aMN = d("auxiliary_operations_threads", 1);
        aMO = BC.g(timeUnit2, 10L, "fullscreen_ad_pending_display_state_timeout_ms");
        aMP = BC.g(timeUnit, 2L, "fullscreen_ad_showing_state_timeout_ms");
        aMQ = d("lhs_close_button_video", bool);
        aMR = d("close_button_right_margin_video", 4);
        aMS = d("close_button_size_video", 30);
        aMT = d("close_button_top_margin_video", 8);
        aMU = d("video_countdown_clock_margin", 10);
        aMV = d("video_countdown_clock_gravity", 83);
        aMW = d("countdown_clock_size", 32);
        aMX = d("countdown_clock_stroke_size", 4);
        aMY = d("countdown_clock_text_size", 28);
        aMZ = d("draw_countdown_clock", bool2);
        aNa = d("inter_display_delay", 200L);
        aNb = d("maximum_close_button_delay_seconds", 999L);
        aNc = d("respect_close_button", bool2);
        aNd = d("lhs_skip_button", bool2);
        aNe = d("mute_controls_enabled", bool);
        aNf = d("allow_user_muting", bool2);
        aNg = d("mute_videos", bool);
        aNh = d("show_mute_by_default", bool);
        aNi = d("mute_with_user_settings", bool2);
        aNj = d("mute_button_size", 32);
        aNk = d("mute_button_margin", 10);
        aNl = d("mute_button_gravity", 85);
        aNm = d("progress_bar_step", 25L);
        aNn = d("progress_bar_scale", 10000);
        aNo = d("progress_bar_vertical_padding", -8);
        aNp = d("vs_buffer_indicator_size", 50);
        aNq = d("video_zero_length_as_computed", bool);
        aNr = d("set_poststitial_muted_initial_delay_ms", 500L);
        aNs = d("fasuic", bool2);
        aNt = d("fsahrpg", bool2);
        aNu = d("eaafrwsoa", bool2);
        aNv = d("postitial_progress_bar_step_ms", 25L);
        aNw = d("postitial_progress_bar_on_bottom", bool2);
        aNx = d("postitial_progress_bar_vertical_padding", -8);
        aNy = d("postitial_progress_bar_scale", 10000);
        aNz = d("sutfaa", bool2);
        aNA = d("fahosu", bool);
        aNB = d("nsuttcl", bool);
        aNC = d("submit_postback_timeout", Integer.valueOf((int) timeUnit2.toMillis(10L)));
        aND = d("submit_postback_retries", 4);
        aNE = d("max_postback_attempts", 3);
        aNF = d("max_persisted_postbacks", 100);
        aNG = d("submit_web_tracker_timeout", Integer.valueOf((int) timeUnit2.toMillis(7L)));
        aNH = d("sossp", bool);
        aNI = d("spp", bool2);
        aNJ = d("retry_on_all_errors", bool);
        aNK = d("get_retry_delay_v1", Integer.valueOf((int) timeUnit2.toMillis(10L)));
        aNL = d("http_connection_timeout", Integer.valueOf((int) timeUnit2.toMillis(30L)));
        aNM = d("http_socket_timeout", Integer.valueOf((int) timeUnit2.toMillis(20L)));
        aNN = d("force_ssl", bool);
        aNO = d("fetch_ad_connection_timeout", Integer.valueOf((int) timeUnit2.toMillis(30L)));
        aNP = d("fetch_ad_retry_count_v1", 1);
        aNQ = d("faer", bool);
        aNR = d("faroae", bool);
        aNS = d("submit_data_retry_count_v1", 1);
        aNT = d("response_buffer_size", 16000);
        aNU = d("fetch_basic_settings_connection_timeout_ms", Integer.valueOf((int) timeUnit2.toMillis(10L)));
        aNV = d("fetch_basic_settings_retry_count", 3);
        aNW = d("fetch_basic_settings_on_reconnect", bool);
        aNX = d("skip_fetch_basic_settings_if_not_connected", bool);
        aNY = d("fetch_basic_settings_retry_delay_ms", Integer.valueOf((int) timeUnit2.toMillis(2L)));
        aNZ = d("idflrwbe", bool);
        aOa = d("falawpr", bool);
        aOb = d("sort_query_parameters", bool);
        aOc = BC.g(timeUnit2, 10L, "communicator_request_timeout_ms");
        aOd = d("communicator_request_retry_count", 3);
        aOe = BC.g(timeUnit2, 2L, "communicator_request_retry_delay_ms");
        aOf = d("rfbsd_ms", -1L);
        aOg = d("ehkpd_ms", 500L);
        aOh = d("rironc", bool);
        aOi = d("rroncbd", bool);
        aOj = BC.g(timeUnit2, 5L, "wverc_ms");
        aOk = d("ad_session_minutes", 60);
        aOl = d("session_tracking_cooldown_on_event_fire", bool2);
        aOm = d("session_tracking_resumed_cooldown_minutes", 90L);
        aOn = d("session_tracking_paused_cooldown_minutes", 90L);
        aOo = d("dc_v2", bool);
        aOp = d("dce", bool2);
        aOq = d("qq", bool);
        aOr = d("qq1", bool2);
        aOs = d("qq2", bool2);
        aOt = d("qq3", bool2);
        aOu = d("qq4", bool2);
        aOv = d("qq5", bool2);
        aOw = d("qq6", bool2);
        aOx = d("qq7", bool2);
        aOy = d("qq8", bool2);
        aOz = d("qq9", bool);
        aOA = d("qq10", bool2);
        aOB = d("qq11", bool2);
        aOC = d("pui", bool2);
        aOD = d("plugin_version", "");
        aOE = d("hgn", bool2);
        aOF = d("cso", bool2);
        aOG = d("cfs", bool2);
        aOH = d("cmi", bool2);
        aOI = d("crat", bool2);
        aOJ = d("cvs", bool2);
        aOK = d("caf", bool2);
        aOL = d("cf", bool2);
        aOM = d("cmtl", bool2);
        aON = d("cnr", bool2);
        aOO = d("ccr", bool);
        aOP = d("adr", bool2);
        aOQ = d("volume_normalization_factor", Float.valueOf(6.6666665f));
        aOR = d("system_user_agent_collection_enabled", bool);
        aOS = d(AppLovinSdkExtraParameterKey.USER_AGENT_COLLECTION_ENABLED, bool);
        aOT = d("collect_device_angle", bool2);
        aOU = d("collect_device_movement", bool2);
        aOV = d("cipc", bool2);
        aOW = d("movement_degradation", Float.valueOf(0.75f));
        aOX = d("device_sensor_period_ms", 250);
        aOY = d("idcw", bool);
        aOZ = d("fetch_basic_settings_delay_ms", 1500);
        aPa = d("mps", "");
        aPb = d("mpsl", 3);
        aPc = d("mpis", "com.applovin,dalvik,java,android,com.android");
        aPd = d("cmps", bool);
        aPe = d("dcttl_1_seconds", 5);
        aPf = d("dcttl_2_seconds", 30);
        aPg = d("dcttl_3_seconds", Integer.valueOf((int) timeUnit.toSeconds(1L)));
        aPh = d("dcttl_4_seconds", Integer.valueOf((int) timeUnit.toSeconds(30L)));
        aPi = d("dcttl_5_seconds", Integer.valueOf((int) TimeUnit.HOURS.toSeconds(1L)));
        aPj = d("dcttl_6_seconds", Integer.valueOf((int) timeUnit3.toSeconds(1L)));
        aPk = d("cclia", bool2);
        aPl = d("lccdm", 10L);
        aPm = d("lmfd", 2);
        aPn = d("is_track_ad_info", bool2);
        aPo = d("submit_ad_stats_max_count", 500);
        aPp = d("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
        aPq = d("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
        aPr = d("vast_max_response_length", 640000);
        aPs = d("vast_max_wrapper_depth", 5);
        aPt = d("vast_unsupported_video_extensions", "ogv,flv");
        aPu = d("vast_unsupported_video_types", "video/ogg,video/x-flv");
        aPv = d("vast_validate_with_extension_if_no_video_type", bool2);
        aPw = d("vast_video_selection_policy", Integer.valueOf(n.a.MEDIUM.ordinal()));
        aPx = d("vast_wrapper_resolution_retry_count_v1", 1);
        aPy = d("vast_wrapper_resolution_connection_timeout", Integer.valueOf((int) timeUnit2.toMillis(30L)));
        aPz = d("vast_industry_icon_max_size", 20);
        aPA = d("vast_industry_icon_margin", 12);
        aPB = d("vast_industry_icon_gravity", 85);
        aPC = d("vast_native_mute_button_size", 24);
        aPD = d("vast_native_play_pause_button_size", 24);
        aPE = d("vast_native_video_widget_padding", 6);
        aPF = d("vast_native_video_widget_alpha", Float.valueOf(0.5f));
        aPG = d("vast_native_video_widgets_enabled", bool2);
        aPH = d("vast_replay_video_upon_completion", bool2);
        aPI = d("vast_replay_icon_size", 64);
        aPJ = d("vcjfhr", bool);
        aPK = d("vcjfhrr", "(?:<|%3C)script[^>]*src=\"(https[^\"]*\\.js[^\"]*)\".*?(?:>|%3E)");
        aPL = d("ree", bool2);
        p.a aVar = p.a.DEFAULT;
        aPM = d("ree_t", Integer.valueOf(aVar.getValue()));
        aPN = d("btee", bool2);
        aPO = d("btet", Integer.valueOf(aVar.getValue()));
        aPP = d("reetoa", bool);
        aPQ = d("reet_msfs", Integer.valueOf(aVar.getValue()));
        aPR = d("reet_msma", Integer.valueOf(p.a.V2.getValue()));
        aPS = d("reet_msmd", Integer.valueOf(aVar.getValue()));
        aPT = d("reet_asfp", Integer.valueOf(aVar.getValue()));
        aPU = d("reet_asfg", Integer.valueOf(aVar.getValue()));
        aPV = d("reet_aset", Integer.valueOf(aVar.getValue()));
        aPW = d("reet_esdi", Integer.valueOf(aVar.getValue()));
        aPX = d("reet_esrp", Integer.valueOf(aVar.getValue()));
        aPY = d("apdra", bool);
        aPZ = d("apdrfs", bool);
        aQa = d("apdrma", bool);
        aQb = d("apdrmd", bool);
        aQc = d("apdrfa", bool);
        aQd = d("apdrev", bool);
        aQe = d("apdrdi", bool);
        aQf = d("apdrrp", bool);
        aQg = d("server_timestamp_ms", 0L);
        aQh = d("device_timestamp_ms", 0L);
        aQi = d("gzip_min_length", 0);
        aQj = d("gzip_encoding_default", bool);
        aQk = d("fetch_settings_gzip", bool);
        aQl = d("device_init_gzip", bool);
        aQm = d("fetch_ad_gzip", bool);
        aQn = d("event_tracking_gzip", bool);
        aQo = d("reward_postback_gzip", bool);
        aQp = d("handle_render_process_gone", bool2);
        aQq = d("rworpg", bool2);
        aQr = d("fdadaomr", bool2);
        aQs = d("teorpc", bool);
        aQt = d("set_webview_render_process_client", bool);
        aQu = d("disable_webview_hardware_acceleration", bool);
        aQv = d("anr_detection_enabled", bool);
        aQw = d("anr_trigger_millis", 4000L);
        aQx = d("anr_touch_millis", 3000L);
        aQy = d("anr_check_millis", 3000L);
        aQz = d("uobid", bool2);
        aQA = d("bvde", bool);
        aQB = d("bvdidm", 1000L);
        aQC = d("bvdim", 4000L);
        aQD = d("bvdrs", 10);
        aQE = d("bvdct", 230);
        aQF = d("bvad", bool);
        aQG = d("bvebb", bool2);
        aQH = d("bvscb", bool2);
        aQI = d("apsobt", bool2);
        aQJ = d("tmtp", 1);
        aQK = d("ntp", 5);
        aQL = d("uwtm", bool);
        aQM = d("dwvvb", bool);
        aQN = d("stcpc", bool2);
        aQO = d("stcic", bool2);
        aQP = d("ueeem", bool);
        aQQ = d("upspfopsu", bool);
        aQR = d("clacaf", bool);
        aQS = d("qjscwwvl", bool);
        aQT = d("config_consent_dialog_state", AppLovinMediationProvider.UNKNOWN);
        aQU = d("country_code", "");
        aQV = d("consent_flow_doc_url", "https://dash.applovin.com/documentation/mediation/android/getting-started/integration#enabling-max-built-in-consent-flow");
        aQW = d("consent_flow_unity_doc_url", "https://dash.applovin.com/documentation/mediation/unity/getting-started/integration#max-built-in-consent-flow");
        aQX = d("cfadtml", 20);
        aQY = d("ps_etr", bool);
        aQZ = BC.g(timeUnit3, 7L, "ps_tri_ms");
        aRa = d("ps_ftri_ms", -1L);
        aRb = d("ps_sroftr", bool);
        aRc = d("ps_sroftrof", bool);
        aRd = d("communicator_enabled", bool2);
        aRe = d("adse", bool2);
    }

    public b(String str, T t) {
        if (str != null) {
            if (t != null) {
                this.name = str;
                this.aKj = t;
                return;
            }
            throw new IllegalArgumentException("No default value specified");
        }
        throw new IllegalArgumentException("No name specified");
    }

    public static Collection<b<?>> JE() {
        return Collections.synchronizedCollection(aKi.values());
    }

    public static <T> b<T> d(String str, T t) {
        if (t != null) {
            if (aKh.contains(t.getClass())) {
                b<T> bVar = new b<>(str, t);
                Map<String, b<?>> map = aKi;
                if (!map.containsKey(str)) {
                    map.put(str, bVar);
                    return bVar;
                }
                throw new IllegalArgumentException(AbstractC2612wf.u("Setting has already been used: ", str));
            }
            throw new IllegalArgumentException("Unsupported value type: " + t.getClass());
        }
        throw new IllegalArgumentException("No default value specified");
    }

    public T JD() {
        return this.aKj;
    }

    public T af(Object obj) {
        return (T) this.aKj.getClass().cast(obj);
    }

    @Override // java.lang.Comparable
    public int compareTo(Object obj) {
        if (obj instanceof b) {
            return this.name.compareTo(((b) obj).getName());
        }
        return 0;
    }

    public String getName() {
        return this.name;
    }
}
